from pathlib import PurePosixPath
from re import sub
from urllib.parse import unquote, urlparse

from molx.config import MAX_TITLE_LENGTH

GENERIC_TITLES = {
    "",
    "-",
    "--",
    "****",
    "n/a",
    "na",
    "none",
    "null",
    "title",
    "untitled",
    "unknown",
    "generated by open babel",
    "generated by openbabel",
    "openbabel",
}

COMPRESSED_SUFFIXES = {".gz", ".bz2", ".xz", ".zip"}
STRUCTURE_SUFFIXES = {".xyz", ".pdb", ".ent", ".sdf", ".mol", ".mol2", ".cif", ".mcif", ".cube", ".cub"}


def clean_title(value: str | None) -> str | None:
    if value is None:
        return None

    title = sub(r"[\x00-\x1f\x7f]+", " ", str(value))
    title = sub(r"\s+", " ", title).strip(" \t\r\n\"'")
    if not title:
        return None

    if title.lower() in GENERIC_TITLES:
        return None

    return title[:MAX_TITLE_LENGTH]


def unquote_cif_value(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def read_cif_multiline(lines: list[str], start_index: int) -> tuple[str | None, int]:
    if start_index >= len(lines):
        return None, start_index

    first = lines[start_index]
    if not first.startswith(";"):
        return unquote_cif_value(first), start_index

    values = [first[1:]]
    for index in range(start_index + 1, len(lines)):
        line = lines[index]
        if line.startswith(";"):
            return "\n".join(values), index
        values.append(line)
    return "\n".join(values), len(lines) - 1


def extract_xyz_title(lines: list[str]) -> str | None:
    if len(lines) < 2:
        return None
    return clean_title(lines[1])


def extract_pdb_title(lines: list[str]) -> str | None:
    title_parts = [line[10:].strip() for line in lines if line.startswith("TITLE")]
    title = clean_title(" ".join(title_parts))
    if title:
        return title

    for prefix in ("HEADER", "COMPND"):
        for line in lines:
            if line.startswith(prefix):
                title = clean_title(line[10:].strip())
                if title:
                    return title
    return None


def extract_sdf_title(lines: list[str]) -> str | None:
    return clean_title(lines[0] if lines else None)


def extract_mol2_title(lines: list[str]) -> str | None:
    for index, line in enumerate(lines[:-1]):
        if line.strip().upper() == "@<TRIPOS>MOLECULE":
            return clean_title(lines[index + 1])
    return None


def iter_cif_values(lines: list[str], keys: tuple[str, ...]):
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            index += 1
            continue

        lower = stripped.lower()
        for key in keys:
            if lower.startswith(key):
                value = stripped[len(key) :].strip()
                if value and value != ";":
                    yield unquote_cif_value(value)
                elif index + 1 < len(lines):
                    value, index = read_cif_multiline(lines, index + 1)
                    if value:
                        yield value
        index += 1


def extract_cif_title(lines: list[str]) -> str | None:
    keys = (
        "_chemical_name_common",
        "_chemical_name_systematic",
        "_struct.title",
    )
    for value in iter_cif_values(lines, keys):
        title = clean_title(value)
        if title:
            return title

    for line in lines:
        stripped = line.strip()
        if stripped.lower().startswith("data_"):
            title = clean_title(stripped[5:].replace("_", " "))
            if title:
                return title
    return None


def extract_cube_title(lines: list[str]) -> str | None:
    for line in lines[:2]:
        title = clean_title(line)
        if title:
            return title
    return None


def extract_structure_title(data: str, format_name: str) -> str | None:
    lines = data.splitlines()
    extractors = {
        "xyz": extract_xyz_title,
        "pdb": extract_pdb_title,
        "sdf": extract_sdf_title,
        "mol": extract_sdf_title,
        "mol2": extract_mol2_title,
        "cif": extract_cif_title,
        "cube": extract_cube_title,
    }
    extractor = extractors.get(format_name.lower())
    if not extractor:
        return None
    return extractor(lines)


def title_from_url(url: str) -> str | None:
    parsed = urlparse(url)
    filename = PurePosixPath(unquote(parsed.path)).name
    if not filename:
        return None

    path = PurePosixPath(filename)
    stem = path.name
    if path.suffix.lower() in COMPRESSED_SUFFIXES:
        stem = PurePosixPath(path.stem).name
    suffix = PurePosixPath(stem).suffix.lower()
    if suffix in STRUCTURE_SUFFIXES:
        stem = PurePosixPath(stem).stem

    stem = stem.replace("_", " ").replace("-", " ")
    return clean_title(stem)


def normalize_custom_title(title: str | None) -> str | None:
    return clean_title(title)


def infer_structure_title(data: str, format_name: str, url: str) -> str | None:
    return extract_structure_title(data, format_name) or title_from_url(url)
